### ISSUE TITLE
ckeditor - Paste from word popup not opening in IE11

### ISSUE THREAD

**Issue by shamikedfx** [ckeditor/ckeditor-sdk#128]
Hello,

I am using CK editor version 4.3.4 .
The problem is that, the popup of the button Paste from word is not opening in IE (11 - checked). 
Only allow access small window is opening and after clicking "Allow access" button it directly paste the content in the editor without opening the Paste from word popup.
But it is working fine in other browser like Firefox , Crome etc.

Could you please look the issue ?
Thanks in advance.

Best regards,
Shamik

**Comment by jswiderski** [comment]
This is Ie default setting in IEs. There is nothing we can do about it from JS level- http://superuser.com/questions/476210/disable-do-you-want-to-allow-this-webpage-to-access-your-clipboard-message.

**Comment by Reinmar** [comment]
Besides that, this is not the right place to report bugs in CKEditor. Next time please do that on http://dev.ckeditor.com
