### ISSUE TITLE
one insertText leads to multiple insertion in the editor 

### ISSUE THREAD

**Issue by interstellerS** [ckeditor/ckeditor-sdk#130]
In some cases , when i paste data in ckeditor the text copied is duplicated multiple times (2 , 4 sometimes 8 ) .
The same issues occurs sometimes with the insertText Method : 
ex :  the code is insertText('beep')  ---> the text inserted is 'beep beep beep beep'.

Unfortunately the issue is rare and i straggle to reproduce it everytime .
Tho , I noticed that this behaviour may occur after heavy use of ckeditor (paste large amout of text etc etc ) .

In thoses cases when i debug the ckeditor  i see many listners to insertText event (in the normal flow i see just one ) . 

I guess in some heavier use of ckeditor , the same listner to insertText is register multiple times causing this weired behaviour .

Even if the reason may be not clear , I wonder if there is some workaround like reinitialize all listners before setting text .

Any help whould be truly appreciated since this bug is random and  may affect clients data .

**Comment by AnnaTomanek** [comment]
This repository contains the sources of [CKEditor SDK](http://sdk.ckeditor.com/). Please use CKEditor bug tracker to report issues in CKEditor itself: http://dev.ckeditor.com/

Thanks!

**Comment by SantoshGudla** [comment]
Iam getting this Duplicates issue when i inserting,make sure to resolve
