### ISSUE TITLE
MathJax code in repository and it's license.

### ISSUE THREAD

**Issue by adelura** [ckeditor/ckeditor-sdk#131]
According to [issue:12948](http://dev.ckeditor.com/ticket/12948):

> MathJax is under Apache licence which we can not use in our project so we should not use MathJax CDN directly. We can make it configurable and let user choose does he want and can use Apache licence.

 I wonder whether we are allowed to keep mathJax source code in our repository.

**Comment by Reinmar** [comment]
SDK is licensed differently than CKEditor and it's not part of the CKEditor project, so I don't think there's a problem here.

See: sdk.ckeditor.com/license.html

**Comment by adelura** [comment]
@wwalc  said:
> MIT applies to the source code examples we provide so that people could reuse them in any place they want.
>SDK itself has this clause: "All libraries and components included in the CKEditor SDK are licensed under the terms of their own respective licenses. This pertains, but is not limited to, the following: (...)
>So mathjax can exist in SDK
