### ISSUE TITLE
[major] SCAYT and WSC doesn't work in offline version

### ISSUE THREAD

**Issue by adelura** [ckeditor/ckeditor-sdk#134]
These plugins are not available in ckeditor submodule plugins directory. They should be include as a submodule or ideally in package.json. Related repos are here: https://github.com/WebSpellChecker. Whole process should be done in builder.

**Comment by adelura** [comment]
The problem exists only in a `major` branch which currently uses https://github.com/ckeditor/ckeditor-dev submodule which by default doesn't include such plugins. On `master` branch we use https://github.com/ckeditor/ckeditor-releases submodule which include them.

We created a major branch for testing purposes. So the problem to solve is to fit SDK builder to work with unpublished versions. It might be available by allow SDK builder to build a release version of CKEditor using [CKBuilder](https://github.com/ckeditor/ckbuilder), and then work on it.

**Comment by Reinmar** [comment]
Fixed when we started building using CKEditor presets repo.
