### ISSUE TITLE
No information about pasteFilter in webkit browsers

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor-sdk#140]
In samples/acf.html there are a few examples of how allowedContent flag works. Unfortunately on webkit based browsers, from user's point of view, they don't work as expected.

When I select content from provided example ("A sample heavily formatted text using different fonts and text colors.") and try to paste it into the third editor, I lose most of formatting. This happens because of pasteFilter. There is no mention in docs about pasteFilter and additional filtering on Opera/Chrome. Docs should be updated beacuse currently it looks like a bug.

**Comment by Reinmar** [comment]
Plus https://github.com/ckeditor/ckeditor-docs/commit/1883d71b942207d640641c42c18889a9db7130cc

**Comment by Reinmar** [comment]
Influenced by PJ I changed my mind - it's easier to disable the paste filter in this sample - fixed in 8067ad7.
