### ISSUE TITLE
Links should be links - broken user experience

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor-sdk#147]
Example page: http://sdk.ckeditor.com/samples/fileupload.html#uploading-dropped-and-pasted-images.

Go to last section: "Get Sample Source Code" and open **links** in new page, either by doing middle mouse click or by using context menu open link in new page.
Oddly enough they links to not-existing page: http://sdk.ckeditor.com/samples/1.

This is huge WTF because when someone totally new to CKEditor docs will see links and try them to open in new page they will see that this is not working.

The link looks exactly like any other link and there is no indication that it opens modal.
If I didn't ask someone from team I wouldn't know that this opens modal.

Solution: make this "open source code" thing something different, button maybe - so user will not confuse it with regular link.

**Comment by jodator** [comment]
BTW, The middle mouse button trick works in Firefox, since Chrome override this behavior.

**Comment by Reinmar** [comment]
I described a solution in https://github.com/ckeditor/ckeditor-sdk/pull/156#issuecomment-134957447.

**Comment by Reinmar** [comment]
Fixed with #161.
