### ISSUE TITLE
The offline version has documentation that links to sdk.ckeditor.com

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-sdk#149]
In older versions of SDK, links inside CKEditor documentation linked to an offline SDK sample. See e.g. the following package: http://sdk.ckeditor.com/ckeditor_4.4.7_sdk.zip and demo linked at the bottom of `ckeditor_sdk/docs/index.html#!/guide/dev_shortcuts`

There is a code that should handle this but somehow 
https://github.com/ckeditor/ckeditor-sdk/blob/39f0a82d6b294f34c1ed5d7052da1f6096bcc64c/dev/builder/app.js#L654
is not executed.

**Comment by Reinmar** [comment]
Fixed by #155.
