### ISSUE TITLE
How to convert MS Word Smart Quotes and em-dashes to simple quotes and dashes in Ckeditor 4

### ISSUE THREAD

**Issue by dawnbuie** [ckeditor/ckeditor-sdk#172]
Hi I really like the new Ckeditor 4 Advanced Content Filtering along with the pastefromword plugin - and have read the docs on what html tags to allow and not, and I understand why it kindly converts my client's MS Word crap into htmlentities. However, I'd like to do a little intervention and convert the smart quotes to straight quotes - and all em dashes to plain dashes and not allow   - before the text gets sent to the CMS database. But I can't find any docs on this or examples.

I can see there were many questions about this on the old forum Ckeditor forum http://ckeditor.com/forums/CKEditor-3.x/Replacing-smart-quotes-regular-quotes, http://ckeditor.com/forums/CKEditor-3.x/Problem-copyingpasting-MS-Word but they didn't get answered.

Please note I've also asked this question here http://stackoverflow.com/questions/34866570/how-to-convert-ms-word-smart-quotes-and-em-dashes-to-simple-quotes-and-dashes-in

**Comment by Reinmar** [comment]
This is CKEditor SDK's issue tracker, so not a good place for asking questions. StackOverflow is much better :).

**Comment by dawnbuie** [comment]
Ah well no one has answered. Perhaps you could add information on how to modify what gets output as an htmlentity into the documentation?

**Comment by mlewand** [comment]
It's quite fresh question, we usually answer after 24h so that CKEditor community has also a chance to engage. Don't worry we'll keep an eye at your question. :)
