### ISSUE TITLE
missing files for "file:///MY_PATH/ckeditor-sdk-master/samples/A_SAMPLE.html"

### ISSUE THREAD

**Issue by AL-X-dev** [ckeditor/ckeditor-sdk#189]
Attempting to look at samples, the ckeditor fails to find required files.  For example, attempting to look at "uicolor.html", like this:

```
    file:///MY_PATH/ckeditor-sdk-master/samples/uicolor.html
```

The page comes up with "ckeditor" inactive.  Using development tools in browser, I see this in console:

```
file:///MY_PATH/ckeditor-sdk-master/template/theme/css/sdk.css       Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///MY_PATH/ckeditor-dev/ckeditor.js             Failed to load resource: net::ERR_FILE_NOT_FOUND
```

Looking at the first error message, I checked and indeed there is no "css" sub-directory.

Looking at the second error message, I'm curious where the top-level directory "ckeditor-dev/" is supposed to come from.  Am I supposed to build something before I can look at samples?  That's not very friendly.

Alexander (AL_X_Dev)

**Comment by mlewand** [comment]
Well, yes - probably you're missing CSS files built from SASS.

Take a moment and go though commands in [readme file](https://github.com/ckeditor/ckeditor-sdk/blob/master/README.md) and let us know if running these commands fixed the issue for you.
