### ISSUE TITLE
Writing other languages in an Arabic editor alters special characters

### ISSUE THREAD

**Issue by zebu05** [ckeditor/ckeditor-sdk#190]
http://sdk.ckeditor.com/samples/uilanguages.html

Using the link above, I set the language to Arabic.

1. Type any words in Arabic
2. Copy the following {AF_FIRST_NAME}
3. Try writing in English after, and see how the curly brackets changes.

**Comment by f1ames** [comment]
Hello @zebu05,
while you noticed this issue browsing CKEditor 4 SDK, it is a CKEditor 4 issue. I would ask you to report it in the CKEditor 4 bug tracker - http://dev.ckeditor.com/. Thanks!
