### ISSUE TITLE
Meta tags not prepopulating in Document Properties plugin

### ISSUE THREAD

**Issue by MarkAtXert** [ckeditor/ckeditor-sdk#191]
Hi all, this is my first bug report _in my life_ on Github so advance apologies if I'm doing this wrong.

In the Document Properties plugin (http://sdk.ckeditor.com/samples/fullpage.html), as a user I would expect the Meta Tags fields (Author, Copyright, etc.) to prepopulate with existing data, much as the Page Title, Document Type Heading, etc. do.  However, they're blank.  

Thanks!

**Comment by f1ames** [comment]
Thanks for reporting @MarkAtXert. However, this is not the correct place to report issues related to CKEditor 4. This is CKEditor 4 SDK repository so it is a place for SDK related issue.
I would ask you to report this issue in our [official bug tracker](http://dev.ckeditor.com/). Thank you!

**Comment by MarkAtXert** [comment]
Thanks!  I started to report it there, but the link at the top of the full page sample went here so I thought here was the correct place.

Thanks again!
