### ISSUE TITLE
Case sensitive class not applied on Chrome

### ISSUE THREAD

**Issue by cardillator** [ckeditor/ckeditor-sdk#193]
For any extrange reason, dynamically added styles to editor with camel case are not being applied to content elements.

To reproduce:
1. Use a clean CKEditor download
2. Edit config.js and add those lines before the "editorConfig" function:
var cssStylesContenidoInteractivo = [
'.interElem { background:#dddddd; }' ,
].join( '' ).replace(/;/g, ' !important;' );

CKEDITOR.addCss( cssStylesContenidoInteractivo );

3. Comment the config.removeDialogTabs config option
4. Open the editor on Chrome, create a link and set its style to "interElem". The style will not be applied. In the other hand, if you apply the style "interelem" (lower case) the style is applied.

Best regards,
Daniel

**Comment by f1ames** [comment]
Hello @cardillator,
thanks for your input. However, this is ckeditor-sdk repository where only issues related to CKEditor SDK should be reported. I would like to ask you to report this issue on the [official CKEditor bug tracker](http://dev.ckeditor.com/). Thank you!
