### ISSUE TITLE
Add widget styles to styles samples in SDK

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-sdk#194]
Related to http://dev.ckeditor.com/ticket/16644

TODO (after closing #16644)
1. Create SDK sample with widgets styling (extend existing sample, adding widget styling in the middle, above stylesheet parser: http://sdk.ckeditor.com/samples/styles.html), use default styles introduced in 1-2 (do not use styles from http://ckeditor.com/tmp/4.4.0/widget-styles.html, they are nice but cannot be defined using inline CKEditor configuration). Ask Anna what text to move from http://ckeditor.com/tmp/4.4.0/widget-styles.html. We shall not repeat docs in SDK.
1. Update docs about styling with the link to SDK http://docs.ckeditor.com/#!/guide/dev_styles (Ctrl+F: "little demo of widget styling").
1. Add a comment to docs about known limitations: placeholder & http://dev.ckeditor.com/ticket/13818 (definitely nice to have due to styling embed media).
1. To all SDK samples about inserting widgets (e..g http://sdk.ckeditor.com/samples/captionedimage.html) add "Related link" at the bottom to styling widgets.
1. In http://sdk.ckeditor.com/samples/mediaembed.html use style introduced in 1-2 (e.g. 320p).

**Comment by f1ames** [comment]
Created a PR https://github.com/ckeditor/ckeditor-docs/pull/72 covering items 2 and 3.

**Comment by f1ames** [comment]
> In http://sdk.ckeditor.com/samples/mediaembed.html use style introduced in 1-2 (e.g. 320p).

@wwalc In mediamebed sample the `embed` plugin is used. We created custom widget styles only for `embedsemantic` plugin (https://github.com/ckeditor/ckeditor-dev/commit/fbe67fa1330a9d0d90a5f5edf20bbbcd6d2d5b97#diff-5c464e0c121157bc5700bd183aa8913dR122) so those styles cannot be used unless we switch to `embedsemantic` in this sample.

**Comment by wwalc** [comment]
Oops can you try to create a style in CKE4 that will work for both for embedSemantic and embed? Not sure if it is enough to define a style for `embed` and `embedSemantic` will pick it up.
If there is no reasonable way, then let's duplicate styles for the second class as well. 

Sorry for the mess. I completely forgot about `embed` alone.

**Comment by f1ames** [comment]
Ok, I will look into it.
I also created a PR https://github.com/ckeditor/ckeditor-sdk/pull/195 covering item 1 and 4.

**Comment by f1ames** [comment]
> Not sure if it is enough to define a style for embed and embedSemantic will pick it up.

The styles will not be used by `embedSemantic` while defined only for `embed`, so they have to be duplicated. However, while `stylescombo` plugin use styles names as styles ids the names cannot be the same because they got overwritten by the latter definition. Should we change styles names for one of the plugins?

**Comment by f1ames** [comment]
@wwalc Maybe we could use new styles on a new _Widget styles_ sample while mediaembed sample already uses some widget styling (_Narrow media_, _Centered media_)?

**Comment by f1ames** [comment]
Unless we consider fixing this, one idea for a workaround (quite ugly IMHO) could be using unicode entities in one of the group like

```
	{ name: '240p', type: 'widget', widget: 'embed', attributes: { 'class': 'embed-240p' } },
	{ name: '360p', type: 'widget', widget: 'embed', attributes: { 'class': 'embed-360p' } },
	{ name: '480p', type: 'widget', widget: 'embed', attributes: { 'class': 'embed-480p' } },
	{ name: '720p', type: 'widget', widget: 'embed', attributes: { 'class': 'embed-720p' } },
	{ name: '1080p', type: 'widget', widget: 'embed', attributes: { 'class': 'embed-1080p' } },

	{ name: '240&#112;', type: 'widget', widget: 'embedSemantic', attributes: { 'class': 'embed-240p' } },
	{ name: '360&#112;', type: 'widget', widget: 'embedSemantic', attributes: { 'class': 'embed-360p' } },
	{ name: '480&#112;', type: 'widget', widget: 'embedSemantic', attributes: { 'class': 'embed-480p' } },
	{ name: '720&#112;', type: 'widget', widget: 'embedSemantic', attributes: { 'class': 'embed-720p' } },
	{ name: '1080&#112;', type: 'widget', widget: 'embedSemantic', attributes: { 'class': 'embed-1080p' } }
```

it is displayed the same but names are different so works fine as ids.

**Comment by f1ames** [comment]
Created new PR with additional embed styles - https://github.com/ckeditor/ckeditor-dev/pull/302.

**Comment by f1ames** [comment]
To sum up:

1. PR with additional styles set for `embed` plugin have been merged to `major` (with https://github.com/ckeditor/ckeditor-dev/commit/33f3a2a3a687af1c1aa4ba32181aa363f5d79751).
1. PR covering item 2 and 3 is ready for review (https://github.com/ckeditor/ckeditor-docs/pull/72).
1. PR covering item 1, 4 and 5 is also ready for review (https://github.com/ckeditor/ckeditor-sdk/issues/195).

From my side, it is ready. @AnnaTomanek probably would like to do some adjustments in those two PRs. Feel free to do so and when it is ready we can merge it.

**Comment by f1ames** [comment]
I also updated presets so SDK can be build from the latest version of `major`.
