### ISSUE TITLE
Update a11ychecker plugin?

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-sdk#198]
Not sure if the one we use now in demos is fully compatible with 4.6?

**Comment by f1ames** [comment]
It should be built from the latests `master` (latest commit adds compatibility with `moono-lisa` skin - https://github.com/cksource/ckeditor-plugin-a11ychecker/commit/bf7ccf1707e737d032550a4dac3cbc26ed8fb198). Previous builds will work but have no support for a new skin.

**Comment by f1ames** [comment]
Updated to `1.1.0` with https://github.com/ckeditor/ckeditor-sdk/commit/6c1e257e4f4b32daeadb9ecca65425523197008f.

**Comment by AnnaTomanek** [comment]
Looks like it's done in the online version.
