### ISSUE TITLE
Meta data not loading in document properties.

### ISSUE THREAD

**Issue by teamllamauk** [ckeditor/ckeditor-sdk#199]
On the '[Editing Complete HTML Pages](http://sdk.ckeditor.com/samples/fullpage.html)' example there appears to be a problem with the Meta Tags tab.

The source shows there are Meta Tags in the page but they do not load into the Document Properties dialog. Adding a list of keywords to the dialog adds a new meta tag to the source code.

However, when re-opening the document properties dialog the keywords meta tag box is empty.

At this point you can add more keywords which will create another keywords meta tag in the source. 

This can be added indefinitely with more and more meta tags being added to the source.

It is the same for all of the boxes on the meta tags properties page.

**Comment by f1ames** [comment]
@teamllamauk thank you for reporting. This issue was already reported on our [bug tracker](http://dev.ckeditor.com) - [#12624](http://dev.ckeditor.com/ticket/12624). If you would like to add your comments there feel free to do so.
