### ISSUE TITLE
JS error in case of multi drag & drop upload.

### ISSUE THREAD

**Issue by sama55** [ckeditor/ckeditor-sdk#203]
Thank you for a wonderful editor. I found JS error on the D&D sample page. When I upload "multi images" in this page, below error is displayed on my Chrome console. However, the upload itself is processed correctly.

Sample page:
http://sdk.ckeditor.com/samples/fileupload.html#uploading-dropped-and-pasted-images
Error message:
ckeditor.js:430 The given range isn't in document.

The same phenomenon occurs also in my development environment.
Is there a way to avoid this error?
Best regards.

**Comment by f1ames** [comment]
Hello @sama55,
we are happy to hear that you like CKEditor! Thank you for reporting this issue. However, this is ckeditor-sdk repository and while you encounter this error on the SDK page it is issue inside CKEditor and should be reported in our [official bug tracker](http://dev.ckeditor.com/).
I would like to ask you to re-report this issue there with some simple description with steps how to reproduce the issue.

Thank you!

**Comment by wwalc** [comment]
Reported in http://dev.ckeditor.com/ticket/16744

**Comment by sama55** [comment]
Thanks f1ames and wwalc, I got it. Thanks for your advice.
