### ISSUE TITLE
data-cke-real-element-type="anchor"  data-cke-saved-href data-cke-saved-src

### ISSUE THREAD

**Issue by Spiritje** [ckeditor/ckeditor-sdk#206]
CKEditor version : CKEditor 4.6.1 (revision 580bcaf)

I have to delete through PHP those data-cke-saved... that I find in a link or an image.  This workes fine but now I need anchor links and this is impossible. And I really need them. 
Now I got it also in an anchor link but in a worser way.  

This is what the editor made (beside the "id" tag, the rest is normal. The "id" should not even be there)
<p><a id="testing" name="testing"></a></p>

With or without the "id" in the anchor link, once I retrieve it from the database (and it was saved this way into the database !) :  
`<img data-cke-real-element-type="anchor" src="data:image/gif;base64,R0lGODlhAQABAPABAP///wAAACH5BAEKAAAALAAAAAABAAEAAAICRAEAOw==" title="Anchor" alt="Anchor" data-cke-real-node-type="1" data-cke-realelement="%3Ca%20data-cke-saved-name%3D%22testing%22%20name%3D%22testing%22%20id%3D%22testing%22%3E%3C%2Fa%3E" class="cke_anchor" align="">`

Believe it or not, but this WAS originally an anchor link !!!
I disabled other javascripts but it makes no difference, so there's no interference from other javascript. 
So I got these strange lines in an image tag, a normal link and the anchor link. But the anchor link has become an image now. 

As you can see I got a very recent version that I did NOT adapt, I left it in its original state as I downloaded it. 

So I got : 
in an anchor link: data-cke-real-element-type="anchor" 
in a normal link: data-cke-saved-href 
in an image tag: data-cke-saved-src 

I really need the anchor link.  Help needed please...

**Comment by f1ames** [comment]
Hello @Spiritje,
thanks for reporting the possible issue. However, this is the CKEditor SDK repository where issues related only to our SDK should be reported. You can report a bug/issue related to CKEditor in [our official bugtracker](http://dev.ckeditor.com/).
I would like to ask you to report this issue there. If you could also add steps to reproduce the issue (what html should be inserted into editor, what to click, etc) and your CKEditor config that would be great! You can also link this issue there for a reference.

Thank you

**Comment by Spiritje** [comment]
Yes I'll do that. Thanks.
