### ISSUE TITLE
Links does not work in read-only mode

### ISSUE THREAD

**Issue by RisteJovanoski** [ckeditor/ckeditor-sdk#208]
when clicking on link in read-only mode nothing happens...
you can see it here
http://sdk.ckeditor.com/samples/readonly.html

make the editor in read only mode and try to click on the links...

**Comment by mlewand** [comment]
Hi @RisteJovanoski thanks for the report. What's exactly your expected behavior?

If you'd like clicking links to open a page in readonly mode it's a feature request for the CKEditor itself rather than sdk samples. You can report it at dev.ckeditor.com.
