### ISSUE TITLE
Adding a list removes preceding empty line with enterMode = CKEDITOR.ENTER_BR

### ISSUE THREAD

**Issue by caugner** [ckeditor/ckeditor-sdk#209]
## Problem

When using the `CKEDITOR.ENTER_BR` _enterMode_, adding a (numbered or bulleted) list after an empty line removes this preceding line.

## Steps to reproduce

**Step 1**: Go to http://sdk.ckeditor.com/samples/enterkey.html

**Step 2**: Choose _When <kbd>Enter</kbd> is pressed:_ `Break the line with a <br>`
![grafik](https://cloud.githubusercontent.com/assets/495429/24457351/4437082a-1496-11e7-93c5-e2222beb6a41.png)

**Step 3**: Add the following text:
```
Line before empty line

First item
```
![grafik](https://cloud.githubusercontent.com/assets/495429/24457224/de646786-1495-11e7-818c-05072990026d.png)

**Step 4**: Move the cursor to the line containing "First item" and press: 
![grafik](https://cloud.githubusercontent.com/assets/495429/24457150/a91cb682-1495-11e7-9d58-3e07f8917ddb.png)
![grafik](https://cloud.githubusercontent.com/assets/495429/24457246/eb82fd2e-1495-11e7-91f2-e7f990bcfdb6.png)

**Expected behavior**: A list is created with "First item" as its first item, leaving the preceding line intact.
**Actual behavior**: The list is created, but the preceding line is removed (*).

(*) Note that in the example there is a margin between the first line and the list, so that the removal of the line is not necessarily noticable (especially in the example):
![grafik](https://cloud.githubusercontent.com/assets/495429/24457474/aac53670-1496-11e7-805f-0955b2eb8475.png)

## Solutions

The behavior of adding a list (same holds for indentation using the _indentblock_ plug-in) should be changed so that it does not remove a preceding empty line.

It might be desirable to make this behavioral change configurable in order to maintain backward-compatibility.

**Comment by mlewand** [comment]
Thanks for detailed report. However currently we use [Trac](http://dev.ckeditor.com/) for issues related to CKEditor itself. This repository is used solely for our sdk samples.

As for this issue I don't see a strong reason why you'd need a `<br>` before list, since lists are by definition a block elements, and as such require line break. But that's something that should be discussed on Trac.

**Comment by caugner** [comment]
See: https://dev.ckeditor.com/ticket/16948
