### ISSUE TITLE
oEmbed demo doesn't work over SSL

### ISSUE THREAD

**Issue by vokiel** [ckeditor/ckeditor-sdk#221]
There is still one issue on HTTPS with [oEmbed](https://sdk.ckeditor.com/samples/mediaembed.html): pasting links doesn't work.

> This URL could not be automatically embedded.

Checking the command with cURL gives this error:
> http: error: SSLError: hostname 'ckeditor.iframe.ly' doesn't match either of 'iframe.ly', 'www.iframe.ly'

This is known for some time https://ckeditor.com/addon/embed#comment-3013034922

> After some investigation, it turns out that the default configuration using the public Iframely service does not support SSL. If you need SSL support, you should either host Iframely locally on your server or use the public service through the iframe.ly domain with your own API key.

**Comment by vokiel** [comment]
Ref #123

**Comment by iparamonau** [comment]
Please contact me at ivan at iframely.com, we'll give you instructions on how to fix the demo.

**Comment by vokiel** [comment]
Thanks to @iparamonau valid certificate was added to the `ckeditor.iframe.ly` which makes our demo working smoothly over HTTPS!
