### ISSUE TITLE
Adding "0pt" while saving information

### ISSUE THREAD

**Issue by moadattebayo** [ckeditor/ckeditor-sdk#224]
Actually I migrated to CKEditor 4.7.2 after using 4.0, in order to benefit from including tables. However, when I save the table on the rich text, and when I switch to code mode it gives me either 
`0pt<span>{content}</span>`
or
```
0pt<div>
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<caption>Table</caption>
	<tbody>
		<tr>
			<td>1</td>
			<td>2</td>
		</tr>
		<tr>
			<td>3</td>
			<td>4</td>
		</tr>
		<tr>
			<td>5</td>
			<td>6</td>
		</tr>
	</tbody>
</table>

<div>&nbsp;</div>
</div>

``` 
PS : {content} is what's written in the 2nd code 
and it affects the content. How can I solve this problem ?

**Comment by moadattebayo** [comment]
Actually I realized that there was a function switching px to pt, and as for the latest version it makes that issue. I just removed it and it worked :D

**Comment by AnnaTomanek** [comment]
Hi, congratulations on upgrading your CKEditor version :)

Please note that this repository is meant for bugs in CKEditor SDK aka CKEditor samples available at https://sdk.ckeditor.com/.

If you want to report a bug in CKEditor, please refer to its GitHub repository: https://github.com/ckeditor/ckeditor-dev/issues
