### ISSUE TITLE
security issue in chrome while copy paste image from word document.

### ISSUE THREAD

**Issue by madhanjoe** [ckeditor/ckeditor-sdk#225]
copy and paste image and text from word document to ck editor is working fine in IE, same not working in chrome.

**Comment by f1ames** [comment]
Hello @madhanjoe,
this is `ckeditor-sdk` repository, if you would like to report an issue related to CKEditor please use [`ckeditor-dev` issues page](https://github.com/ckeditor/ckeditor-dev/issues).

However, if it is a security issue as mentioned in the title, I would ask you to report it  through [our contact form](http://cksource.com/contact) - selecting _Security reports_ in **Type of inquiry** field.
