### ISSUE TITLE
SDK should use new CKE4 logo and branding colors

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-sdk#234]
Similar to ckeditor/ckeditor-dev#1409.

**Comment by AnnaTomanek** [comment]
Two issues after branding:

* The color of links in SDK is the same as in docs but it doesn't look great with the shade of blue that we have for CKEditor 4:

![screen shot 2018-03-12 at 13 55 41](https://user-images.githubusercontent.com/538321/37284872-6ee12690-25fd-11e8-84a7-dfc7f92da3fc.png)

* The samples (SDK) are sort of a part of the documentation (in CKE5 they are included in the Umberto-generated docs, CKE4 just uses a different engine and a separate page), yet it is not branded in the same way as the docs and samples for other projects.

CKEditor 4 docs:
![screen shot 2018-03-12 at 14 01 29](https://user-images.githubusercontent.com/538321/37285028-e9189114-25fd-11e8-8edb-1130506caff5.png)

CKEditor 5 samples:
![screen shot 2018-03-12 at 14 03 02](https://user-images.githubusercontent.com/538321/37285069-13729c66-25fe-11e8-9994-3d3d120ad04a.png)

Maybe we should use the "documentation" branding for the SDK as well to make it more consistent?
