### ISSUE TITLE
从源码添加内容好像出现bug

### ISSUE THREAD

**Issue by haoyalei** [ckeditor/ckeditor-sdk#247]
从源码添加的HTML代码被格式化，修改了HTML内容，<pre>属性还出现语法错误，到时前台样式比可控制
![pre](https://user-images.githubusercontent.com/15228441/39282427-ee3b6430-493b-11e8-8cc9-1363b406f057.jpg)

**Comment by haoyalei** [comment]
就是用Markdown编写的内容导出的HTML代码，添加到ckeditor编辑器源码里，修改时发现源码错乱，还被格式化了

**Comment by Comandeer** [comment]
This repository contains CKEditor 4 SDK. To report bugs in CKEditor 4, please [file an issue in ckeditor/ckeditor-dev repository](https://github.com/ckeditor/ckeditor-dev/issues/new). Please also note that your issue should be written in English.
