### ISSUE TITLE
Search results are not visible

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-sdk#248]
![screen shot 2018-04-27 at 15 49 47](https://user-images.githubusercontent.com/545175/39365857-a3eb2a6c-4a32-11e8-9232-49daf8d2f63a.png)

**Comment by vokiel** [comment]
Reason is:
https://github.com/ckeditor/ckeditor-sdk/blob/b075259a41a1d50474dd0c3733330cd14a009d64/template/theme/sass/partials/_global.scss#L31
