### ISSUE TITLE
Emoji SDK sample

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-sdk#250]
We need a SDK sample for Emoji plugin created in ckeditor/ckeditor-dev#1746 issue.

Let's start with a simplified sample, not focusing (spending time) on the content, as it will be changed/refined by our content pros later on 🙂

I think the sample should present the following:

* Short hint on how to type emojis.
* Information that there are some tags will not upcast the emoji id (`pre`, `code`). I think we don't have to write about it explicitly, but it's enough to put a pre > code with `:<emoji_code>:` in the sample editor. But I'm open for better options on that. 🙂

Let's put the sample in a "Inserting content" category, right below "Tables with Column Resizing".

**Comment by AnnaTomanek** [comment]
👍 for "Inserting content".
