### ISSUE TITLE
Review balloontoolbar sample - remove 3rd party plugins

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-sdk#270]
It seems that sample:
https://sdk.ckeditor.com/samples/balloontoolbar.html
use non CKSource plugin [open link](https://ckeditor.com/cke4/addon/openlink).
It could be nice to make this sample base on CKSource plugins exclusively.
Plugins are linked as submodule in SDK repository here:
https://github.com/ckeditor/ckeditor-sdk/tree/master/samples/assets/plugins

**Comment by mlewand** [comment]
It uses plugin from a third party provider `m.lewandowski` that we have some influence on 😄 Reason why we did so is that there's just a very small plugin, that CKSource does not need to support to. It's just for demo purpose.
