### ISSUE TITLE
Missing image in balloon toolbar sample

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-sdk#272]
1. Open https://sdk.ckeditor.com/samples/balloontoolbar.html
1. Check the image in the sample.

## Actual

It's missing, gives me a 404. It's linked to https://ckeditor.com/assets/images/bg/spoons.jpg

I guess it randomly fails? I recall facing it some time ago, and then it was available again, so I though there might be something with my internet connection - but here I see it again, it's not a coincidence.

**Comment by jacekbogdanski** [comment]
I'm able to reproduce the issue.
![image](https://user-images.githubusercontent.com/10279586/43014623-11205ccc-8c4d-11e8-9001-40d3f9202f2f.png)

**Comment by mlewand** [comment]
Reason for this is that the sample was hotlinking to an image that got removed `https://ckeditor.com/assets/images/bg/spoons.jpg`.
