### ISSUE TITLE
Paste Not Working for First Time in Edge Browser

### ISSUE THREAD

**Issue by shortPause** [ckeditor/ckeditor-sdk#282]
I'm trying to paste a text on CkEditor but it's not working. Neither CTRL+V Nor Right Click & paste works. This is happening on the very first time when application loads and once it loads and if I try again copying and pasting it then works i.e. on second attempt of copy & paste it's working fine!

Also, the right click and paste is enabled for the first time and once paste is selected then nothing happens and paste also becomes disabled also the copied text somehow disappears from clipboard and it's not there anymore so can't paste anywhere else also!

Ironically the same thing is working fine on Chrome but it's not on Edge Browser(Microsoft Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134)

Tried browsing online but out of luck yet as similar issues were raised with CkEditor but fixed past 4.2 version and I'm using Version 4.9

Opened the same issue on [Stack](https://stackoverflow.com/questions/53317628/paste-not-working-first-time-on-ckeditor-on-edge-browser) also.

**Comment by jswiderski** [comment]
This problem doesn't concern SDK but CKEditor. From what we can see it has also been reported in the correct repository https://github.com/ckeditor/ckeditor-dev/issues/2635 thus we will close this ticket and leave our comments in ticket 2635.
